using System.Collections.Generic;
using Template.Core.Data;
using UnityEngine;

namespace Template.Data
{
    /// <summary>
    /// Generated by Template → Import Master Data from MasterData/sample_items.csv.
    /// Don't edit the asset by hand; edit the CSV and re-import.
    /// </summary>
    public sealed class SampleItemDatabase : ScriptableObject
    {
        [SerializeField] private List<SampleItem> items = new List<SampleItem>();

        public IReadOnlyList<SampleItem> Items => items;

        public void Replace(List<SampleItem> newItems)
        {
            items = newItems;
        }
    }
}
